### ISSUE TITLE
Design Plans for Tower System

### ISSUE THREAD

**Issue by TylerFlar** [UCSD-E4E/radio-telemetry-tracker-docs#15]

**Comment by karan-derebail** [comment]
Possible cable protection mechanisms:
Chrome Wire Loom - https://www.cabletiesandmore.com/convoshield-aluminized-tubing?pid=525&gad_source=4&gclid=Cj0KCQjw_-GxBhC1ARIsADGgDjvXuQhSWv8nHIgGU_03UTGqDrBWidvVVKf-AUn0-_elYdYMuv8niB8aAkEREALw_wcB

Vertical Cable Cover - https://www.cableorganizer.com/categories/cable-management/surface-raceways/wire-guards/#features

Heat Shrink Tubing - https://www.amazon.com/1-5-inch-Waterproof-Shrinkable-Wear-Resistant/dp/B07VLYMXDM?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&smid=A2SF5PF2AN75X7&th=1

**Comment by ntlhui** [comment]
We've previously used https://www.mcmaster.com/catalog/130/1012/7609K3 and https://www.mcmaster.com/catalog/130/1012/75145K32

Please sanitize all links prior to posting.

**Comment by ntlhui** [comment]
I would prefer items be sourced from McMaster Carr, Grainger, or Marshalls Industrial Hardware.  I would strongly discourage sourcing from Amazon.
